name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Always a stable version
      with:
        fetch-depth: 2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.4'

    - name: Install dependencies
      run: flutter pub get

    - name: Run unit tests
      run: flutter test

    - name: Build APK (debug)
      run: flutter build apk --debug # Or --release as required

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2 # Avoiding v3 deprecation issues (v2 was stable)
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
