name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Update to the correct action version

    - name: Set up Flutter
      uses: subosito/flutter-action@v2 # Flutter action (with a correct version)
      with:
        flutter-version: '3.27.4' # Ensure your version is set correctly

    - name: Install dependencies
      run: flutter pub get

    - name: Run unit tests
      run: flutter test

    - name: Build APK (debug)
      run: flutter build apk --debug # Or use --release for release build

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-debug.apk # Path to the built APK
