name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # Using correct checkout action version

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.4'

    - name: Install dependencies
      run: flutter pub get

    - name: Run unit tests
      run: flutter test

    - name: Build APK (debug)
      run: flutter build apk --debug # Use --release for release build

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2 # Correct version of the upload artifact action
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-debug.apk # Correct path to the generated APK
